services:
  loop:
    build: .
    container_name: loop
    ports:
      - "8000:8000"
      - "3000:3000"
    environment:
      LOOP_MUSIC_DIR: /music
    volumes:
      - ./music:/music
    restart: unless-stopped